packages:
  - "sdk"
  - "docs"
  - "experiments/billable"
  - "experiments/yt-dos"
  - "experiments/cutable"
  - "experiments/pitch"
  - "starters/minimal"
  - "starters/prisma"
  - "starters/drizzle"
